<?php
/**
 * Login Presets V2
 */

return array(
    // --- V1 Presets (Updated with Metadata) ---
    'travel' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Travel Explorer',
        'template_category' => 'Travel',
        'thumbnail' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',

        'bg_color' => '#eef2f5',
        'bg_image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_color' => '#000000',
        'overlay_opacity' => '0.3',
        'form_bg' => '#ffffff',
        'form_opacity' => '0.95',
        'form_radius' => '12',
        'form_shadow' => '0 10px 30px rgba(0,0,0,0.2)',
        'btn_bg' => '#00a8ff',
        'btn_color' => '#ffffff',
        'btn_radius' => '6',
        'input_radius' => '6',
        'font_family' => 'Poppins, sans-serif',
        'text_color' => '#333333',
        'link_color' => '#00a8ff',
        'link_hover_color' => '#008bdf',
        'form_width' => '380',
        'alignment' => 'center',
    ),
    'orange' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Orange Flat',
        'template_category' => 'Minimal',
        'thumbnail' => '',

        'bg_color' => '#ffefd5',
        'bg_image' => '',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_color' => '',
        'overlay_opacity' => '0',
        'form_bg' => '#ffffff',
        'form_opacity' => '1',
        'form_radius' => '24',
        'form_shadow' => '0 20px 40px rgba(255,165,0,0.15)',
        'btn_bg' => '#ff7f50',
        'btn_color' => '#ffffff',
        'btn_radius' => '24',
        'input_radius' => '12',
        'font_family' => 'Quicksand, sans-serif',
        'text_color' => '#4a4a4a',
        'link_color' => '#ff7f50',
        'link_hover_color' => '#ff6347',
        'form_width' => '350',
        'alignment' => 'center',
    ),
    'glass' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Glass Aurora',
        'template_category' => 'Glassmorphism',
        'thumbnail' => 'https://images.unsplash.com/photo-1557683316-973673baf926?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',

        'bg_color' => '#1e1e2f',
        'bg_image' => 'https://images.unsplash.com/photo-1557683316-973673baf926?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_color' => '#000000',
        'overlay_opacity' => '0.2',
        'form_bg' => '#ffffff',
        'form_opacity' => '0.15',
        'form_radius' => '20',
        'form_shadow' => '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'btn_bg' => 'rgba(255, 255, 255, 0.25)',
        'btn_color' => '#ffffff',
        'btn_radius' => '10',
        'input_radius' => '10',
        'font_family' => 'Inter, sans-serif',
        'text_color' => '#ffffff',
        'link_color' => '#e0e0e0',
        'link_hover_color' => '#ffffff',
        'form_width' => '360',
        'alignment' => 'center',
    ),
    'dark' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Dark Modern',
        'template_category' => 'Dark Mode',
        'thumbnail' => '',

        'bg_color' => '#121212',
        'bg_image' => '',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_color' => '',
        'overlay_opacity' => '0',
        'form_bg' => '#1e1e1e',
        'form_opacity' => '1',
        'form_radius' => '8',
        'form_shadow' => '0 4px 12px rgba(0,0,0,0.5)',
        'btn_bg' => '#bb86fc',
        'btn_color' => '#000000',
        'btn_radius' => '4',
        'input_radius' => '4',
        'font_family' => 'Roboto, sans-serif',
        'text_color' => '#e0e0e0',
        'link_color' => '#bb86fc',
        'link_hover_color' => '#9965f4',
        'form_width' => '340',
        'alignment' => 'center',
    ),

    // --- V2 Presets ---
    'corporate' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Enterprise Blue',
        'template_category' => 'Corporate',
        'thumbnail' => '',

        'bg_color' => '#f8f9fa',
        'bg_image' => '',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_opacity' => '0',
        'form_bg' => '#ffffff',
        'form_opacity' => '1',
        'form_radius' => '4',
        'form_shadow' => '0 2px 4px rgba(0,0,0,0.08)',
        'btn_bg' => '#0d6efd',
        'btn_color' => '#ffffff',
        'btn_radius' => '4',
        'input_radius' => '4',
        'font_family' => 'Segoe UI, Helvetica, Arial, sans-serif',
        'text_color' => '#212529',
        'link_color' => '#0d6efd',
        'link_hover_color' => '#0a58ca',
        'form_width' => '360',
        'alignment' => 'center',
    ),
    'luxury' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Gold Standard',
        'template_category' => 'Luxury',
        'thumbnail' => '',

        'bg_color' => '#111111',
        'enable_gradient_bg' => '1',
        'gradient_type' => 'radial',
        'gradient_angle' => '180',
        'gradient_color_1' => '#222222',
        'gradient_color_2' => '#000000',
        'form_bg' => '#1a1a1a',
        'form_opacity' => '1',
        'form_radius' => '0',
        'form_shadow' => '0 20px 50px rgba(0,0,0,0.5)',
        'form_border_color' => '#d4af37',
        'form_border_width' => '1',
        'btn_bg' => 'transparent',
        'btn_color' => '#d4af37',
        'btn_radius' => '0',
        'btn_border_width' => '1',
        'btn_border_color' => '#d4af37',
        'btn_text_transform' => 'uppercase',
        'btn_letter_spacing' => '2',
        'btn_hover_bg' => '#d4af37',
        'btn_hover_color' => '#000000',
        'input_radius' => '0',
        'font_family' => 'Playfair Display, serif',
        'text_color' => '#d4af37',
        'link_color' => '#d4af37',
        'link_hover_color' => '#ffffff',
        'form_width' => '400',
        'alignment' => 'center',
    ),
    'cyberpunk' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Night City',
        'template_category' => 'Cyberpunk',
        'thumbnail' => '',

        'bg_color' => '#0b0c10',
        'form_bg' => '#1f2833',
        'form_opacity' => '0.9',
        'form_radius' => '0',
        'form_shadow' => '5px 5px 0px #00ffcc',
        'form_border_color' => '#ff003c',
        'form_border_width' => '2',
        'btn_bg' => '#ff003c',
        'btn_color' => '#ffffff',
        'btn_radius' => '0',
        'btn_text_transform' => 'uppercase',
        'btn_font_weight' => '700',
        'btn_letter_spacing' => '1',
        'btn_hover_bg' => '#00ffcc',
        'btn_hover_color' => '#000000',
        'input_radius' => '0',
        'font_family' => 'Rajdhani, sans-serif',
        'text_color' => '#c5c6c7',
        'link_color' => '#00ffcc',
        'link_hover_color' => '#ff003c',
        'form_width' => '380',
        'alignment' => 'center',
    ),
    'minimal' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Clean Slate',
        'template_category' => 'Minimal',
        'thumbnail' => '',

        'bg_color' => '#ffffff',
        'form_bg' => '#ffffff',
        'form_opacity' => '1',
        'form_radius' => '0',
        'form_shadow' => 'none',
        'btn_bg' => '#000000',
        'btn_color' => '#ffffff',
        'btn_radius' => '0',
        'input_radius' => '0',
        'font_family' => 'Inter, sans-serif',
        'text_color' => '#333333',
        'link_color' => '#000000',
        'link_hover_color' => '#666666',
        'form_width' => '320',
        'alignment' => 'center',
    ),
    'gaming' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Level Up',
        'template_category' => 'Gaming',
        'thumbnail' => '',

        'bg_color' => '#1a1a2e',
        'form_bg' => '#16213e',
        'form_opacity' => '1',
        'form_radius' => '16',
        'form_shadow' => '0 0 20px rgba(233, 69, 96, 0.3)',
        'btn_bg' => '#e94560',
        'btn_color' => '#ffffff',
        'btn_radius' => '8',
        'btn_hover_bg' => '#ff2e4d',
        'btn_animation' => 'pulse',
        'input_radius' => '8',
        'font_family' => 'Orbitron, sans-serif',
        'text_color' => '#ffffff',
        'link_color' => '#e94560',
        'link_hover_color' => '#ffffff',
        'form_width' => '400',
        'alignment' => 'center',
    ),
    'neon' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Neon Glow',
        'template_category' => 'Neon',
        'thumbnail' => '',

        'bg_color' => '#050505',
        'form_bg' => '#111111',
        'form_opacity' => '0.9',
        'form_radius' => '12',
        'form_shadow' => '0 0 15px #39ff14',
        'form_border_color' => '#39ff14',
        'form_border_width' => '1',
        'btn_bg' => 'transparent',
        'btn_color' => '#39ff14',
        'btn_border_width' => '2',
        'btn_border_color' => '#39ff14',
        'btn_radius' => '8',
        'btn_hover_bg' => '#39ff14',
        'btn_hover_color' => '#000000',
        'btn_glow_color' => '#39ff14',
        'input_radius' => '8',
        'font_family' => 'Exo 2, sans-serif',
        'text_color' => '#ffffff',
        'link_color' => '#39ff14',
        'link_hover_color' => '#ffffff',
        'form_width' => '360',
        'alignment' => 'center',
    ),
    'saas' => array(
        'template_version' => '1.0',
        'plugin_version' => '2.0',
        'template_name' => 'Startup Flow',
        'template_category' => 'SaaS',
        'thumbnail' => '',

        'enable_gradient_bg' => '1',
        'gradient_type' => 'linear',
        'gradient_angle' => '135',
        'gradient_color_1' => '#667eea',
        'gradient_color_2' => '#764ba2',
        'form_bg' => '#ffffff',
        'form_opacity' => '1',
        'form_radius' => '16',
        'form_shadow' => '0 15px 35px rgba(0,0,0,0.1)',
        'btn_bg' => '#667eea',
        'btn_color' => '#ffffff',
        'btn_radius' => '8',
        'btn_hover_bg' => '#764ba2',
        'btn_animation' => 'lift',
        'input_radius' => '8',
        'font_family' => 'Nunito, sans-serif',
        'text_color' => '#4a5568',
        'link_color' => '#667eea',
        'link_hover_color' => '#764ba2',
        'form_width' => '380',
        'alignment' => 'center',
    ),
);
