<?php
/**
 * Login Presets
 */

return array(
    'travel' => array(
        'bg_color' => '#eef2f5',
        'bg_image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_color' => '#000000',
        'overlay_opacity' => '0.3',
        'form_bg' => '#ffffff',
        'form_opacity' => '0.95',
        'form_radius' => '12',
        'form_shadow' => '0 10px 30px rgba(0,0,0,0.2)',
        'btn_bg' => '#00a8ff',
        'btn_color' => '#ffffff',
        'btn_radius' => '6',
        'input_radius' => '6',
        'font_family' => 'Poppins, sans-serif',
        'text_color' => '#333333',
        'link_color' => '#00a8ff',
        'link_hover_color' => '#008bdf',
        'form_width' => '380',
        'alignment' => 'center',
    ),
    'orange' => array(
        'bg_color' => '#ffefd5',
        'bg_image' => '',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_color' => '',
        'overlay_opacity' => '0',
        'form_bg' => '#ffffff',
        'form_opacity' => '1',
        'form_radius' => '24',
        'form_shadow' => '0 20px 40px rgba(255,165,0,0.15)',
        'btn_bg' => '#ff7f50',
        'btn_color' => '#ffffff',
        'btn_radius' => '24',
        'input_radius' => '12',
        'font_family' => 'Quicksand, sans-serif',
        'text_color' => '#4a4a4a',
        'link_color' => '#ff7f50',
        'link_hover_color' => '#ff6347',
        'form_width' => '350',
        'alignment' => 'center',
    ),
    'glass' => array(
        'bg_color' => '#1e1e2f',
        'bg_image' => 'https://images.unsplash.com/photo-1557683316-973673baf926?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_color' => '#000000',
        'overlay_opacity' => '0.2',
        'form_bg' => '#ffffff',
        'form_opacity' => '0.15',
        'form_radius' => '20',
        'form_shadow' => '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        // Note: Real glassmorphism needs backdrop-filter which isn't dynamically supported in our current CSS generator,
        // but this will look somewhat like it.
        'btn_bg' => 'rgba(255, 255, 255, 0.25)',
        'btn_color' => '#ffffff',
        'btn_radius' => '10',
        'input_radius' => '10',
        'font_family' => 'Inter, sans-serif',
        'text_color' => '#ffffff',
        'link_color' => '#e0e0e0',
        'link_hover_color' => '#ffffff',
        'form_width' => '360',
        'alignment' => 'center',
    ),
    'dark' => array(
        'bg_color' => '#121212',
        'bg_image' => '',
        'bg_position' => 'center center',
        'bg_size' => 'cover',
        'bg_repeat' => 'no-repeat',
        'overlay_color' => '',
        'overlay_opacity' => '0',
        'form_bg' => '#1e1e1e',
        'form_opacity' => '1',
        'form_radius' => '8',
        'form_shadow' => '0 4px 12px rgba(0,0,0,0.5)',
        'btn_bg' => '#bb86fc',
        'btn_color' => '#000000',
        'btn_radius' => '4',
        'input_radius' => '4',
        'font_family' => 'Roboto, sans-serif',
        'text_color' => '#e0e0e0',
        'link_color' => '#bb86fc',
        'link_hover_color' => '#9965f4',
        'form_width' => '340',
        'alignment' => 'center',
    ),
);
